//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public long Id { get; set; }
        public long Lesson_ID { get; set; }
        public string Operation { get; set; }
        public System.DateTime OnTime { get; set; }
    }
}
