//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public long Id { get; set; }
        public long Subject { get; set; }
        public long Lecturer { get; set; }
        public long Audience { get; set; }
        public long Academic_group { get; set; }
        public System.DateTime Time { get; set; }
        public string Day { get; set; }
        public string Type { get; set; }
    
        public virtual Audience Audience1 { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Lecturer Lecturer1 { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
